# Generated by Django 5.0.7 on 2024-08-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='staus',
            new_name='status',
        ),
    ]
